server:
  port: 9090
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yummify
    username: dev
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: yummify
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    liquibase-schema: liquibase_meta

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/yummify/protocol/openid-connect/certs
          issuers: http://localhost:8080/realms/yummify
      admin:
        auth-uri: http://localhost:8080/realms/master/protocol/openid-connect/token
        username: admin
        password: admin
      yummify:
        uri: http://localhost:8080/admin/realms/yummify

minio:
  minio-url: http://localhost:9000
  access-key: FQT6M88SSBiGJ6LhZ6vq
  secret-key: vhdLjxpVntXfjP4mhhbEiAfmFteRVm0kt7wvF0mZ
  bucket-name: yummify